default_stages: [ pre-commit ]

repos:
#  - repo: local
#    hooks:
#      - id: mypy
#        name: Nox mypy
#        entry: nox -f noxfile.py --session mypy -- fix
#        pass_filenames: false
#        language: system
#        types: [ python ]
#        verbose: true
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: '1.11.1'
    hooks:
      - id: mypy


#  - repo: local
#    hooks:
#      - id: lint
#        name: Nox lint
#        entry: nox -f noxfile.py --session styles -- fix
#        pass_filenames: false
#        language: system
#        types: [ python ]
#        verbose: true
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.2
    hooks:
      - id: ruff
        args: [ --fix ]
        types_or: [ python, pyi, jupyter ]
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]


  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.4.30
    hooks:
      - id: pip-compile
        args: [pyproject.toml, -o, prod-requirements.txt]
        files: ^(pyproject\.toml$|prod\-requirements\.txt$)
      - id: pip-compile
        args: [pyproject.toml, --extra, test, -o, test-requirements.txt]
        files: ^(pyproject\.toml$|test\-requirements\.txt$)
      - id: pip-compile
        args: [pyproject.toml, --all-extras, -o, requirements.txt]
        files: ^(pyproject\.toml$|requirements\.txt$)

